<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="go2w">
  <!-- Gloabal parameters -->
  <xacro:include filename="$(find go2w_description)/urdf/const.xacro"/>

  <xacro:property name="mesh_prefix" value="file://$(find go2w_description)/meshes" />

  <xacro:macro name="leg" params="prefix front left">

    <xacro:if value="${(front == True)}">
        <xacro:property name="front_sign" value=" 1" />
    </xacro:if>
    <xacro:if value="${(front == False)}">
        <xacro:property name="front_sign" value="-1" />
    </xacro:if>
    <xacro:if value="${(left == True)}">
        <xacro:property name="left_sign" value=" 1" />
    </xacro:if>
    <xacro:if value="${(left == False)}">
        <xacro:property name="left_sign" value="-1" />
    </xacro:if>
    
    <!-- Hip -->
    <link name="${prefix}_hip">
      <inertial>
        <origin xyz="${hip_com_x*front_sign} ${hip_com_y*left_sign} ${hip_com_z}" rpy="0 0 0" />
        <mass value="${hip_mass}" />
        <inertia ixx="${hip_ixx}" ixy="${hip_ixy*left_sign*front_sign}" ixz="${hip_ixz*front_sign}" iyy="${hip_iyy}" iyz="${hip_iyz*left_sign}" izz="${hip_izz}" />
      </inertial>
      <visual>
        <xacro:if value="${(left == True) and (front == True)}">
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${(left == False) and (front == True)}">
            <origin rpy="${PI} 0 0" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${(left == True) and (front == False)}">
            <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${(left == False) and (front == False)}">
            <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
        </xacro:if>
        <geometry>
          <mesh filename="${mesh_prefix}/hip.dae" />
        </geometry>
        <material name="深色橡胶_001-effect"><color rgba="0.6717055 0.6924257 0.7742702 1" /></material><material name="Material-effect"><color rgba="0.9 0.95 0.95 1" /></material>
      </visual>
      <collision>
        <origin rpy="${PI/2.0} 0 0" xyz="0 ${hip_offset_col_y*left_sign} 0" />
        <geometry>
            <cylinder length="${hip_length}" radius="${hip_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_hip_joint" type="revolute">
      <origin xyz="${hip_offset_x*front_sign} ${hip_offset_y*left_sign} ${hip_offset_z}" rpy="0 0 0" />
      <parent link="body" />
      <child link="${prefix}_hip" />
      <axis xyz="1 0 0" />
      <xacro:if value="${(left == True)}">
        <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_position_min}" upper="${hip_position_max}"/>
      </xacro:if>
      <xacro:if value="${(left == False)}">
        <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_position_max}" upper="${-hip_position_min}"/>
      </xacro:if>
      <dynamics damping="${hip_damping}" friction="${hip_friction}" />
    </joint>

    <!-- Thigh -->
    <link name="${prefix}_thigh">
      <inertial>
        <origin xyz="${thigh_com_x} ${thigh_com_y*left_sign} ${thigh_com_z}" rpy="0 0 0" />
        <mass value="${thigh_mass}" />
        <inertia ixx="${thigh_ixx}" ixy="${thigh_ixy*left_sign}" ixz="${thigh_ixz}" iyy="${thigh_iyy}" iyz="${thigh_iyz*left_sign}" izz="${thigh_izz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <xacro:if value="${left == True}">
              <mesh filename="${mesh_prefix}/thigh.dae" scale="1 1 1"/>
          </xacro:if>
          <xacro:if value="${left == False}">
              <mesh filename="${mesh_prefix}/thigh_mirror.dae" scale="1 1 1"/>
          </xacro:if>
        </geometry>
        <material name="深色橡胶_003-effect"><color rgba="0.6717055 0.6924257 0.7742702 1" /></material><material name="Material_009-effect"><color rgba="0.9 0.95 0.95 1" /></material>
      </visual>
      <collision>
        <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${thigh_offset_col_z}" />
        <geometry>
          <box size="${thigh_length} ${thigh_width} ${thigh_height}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_thigh_joint" type="revolute">
      <origin xyz="${thigh_offset_x} ${thigh_offset_y*left_sign} ${thigh_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}_hip" />
      <child link="${prefix}_thigh" />
      <axis xyz="0 1 0" />
      <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_position_min}" upper="${thigh_position_max}" />
      <dynamics damping="${thigh_damping}" friction="${thigh_friction}" />
    </joint>

    <!-- Calf -->
    <link name="${prefix}_calf">
      <inertial>
        <origin xyz="${calf_com_x} ${calf_com_y*left_sign} ${calf_com_z}" rpy="0 0 0" />
        <mass value="${calf_mass}" />
        <inertia ixx="${calf_ixx}" ixy="${calf_ixy*left_sign}" ixz="${calf_ixz}" iyy="${calf_iyy}" iyz="${calf_iyz*left_sign}" izz="${calf_izz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <xacro:if value="${left == True}">
              <mesh filename="${mesh_prefix}/calf.stl" />
            </xacro:if>
            <xacro:if value="${left == False}">
              <mesh filename="${mesh_prefix}/calf_mirror.stl" />
            </xacro:if>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${calf_rotation_col_p} 0" xyz="${calf_offset_col_x} 0 ${calf_offset_col_z}" />
        <geometry>
          <cylinder length="${calf_length}" radius="${calf_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_calf_joint" type="revolute">
      <origin xyz="${calf_offset_x} ${calf_offset_y*left_sign} ${calf_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}_thigh" />
      <child link="${prefix}_calf" />
      <axis xyz="0 1 0" />
      <limit lower="${calf_position_min}" upper="${calf_position_max}" effort="${calf_torque_max}" velocity="${calf_velocity_max}" />
      <dynamics damping="${calf_damping}" friction="${calf_friction}" />
    </joint>

    <!-- Calf lower -->
    <link name="${prefix}_calflower">
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${calf_lower_length}" radius="${calf_lower_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_calflower_joint" type="fixed">
      <origin xyz="${calf_lower_offset_x} ${calf_lower_offset_y*left_sign} ${calf_lower_offset_z}" rpy="0 ${calf_lower_rotation_p} 0" />
      <parent link="${prefix}_calf" />
      <child link="${prefix}_calflower" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- Calf flower 1 -->
    <link name="${prefix}_calflower1">
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${calf_lower1_length}" radius="${calf_lower1_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_calflower1_joint" type="fixed">
      <origin xyz="${calf_lower1_offset_x} ${calf_lower1_offset_y*left_sign} ${calf_lower1_offset_z}" rpy="${calf_lower1_rotation_p}" />
      <parent link="${prefix}_calflower" />
      <child link="${prefix}_calflower1" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- Foot motor -->
    <link name="${prefix}_foot_motor">
      <inertial>
        <origin xyz="${foot_motor_com_x} ${foot_motor_com_y} ${foot_motor_com_z}" rpy="0 0 0" />
        <mass value="${foot_motor_mass}" />
        <inertia ixx="${foot_motor_ixx}" ixy="${foot_motor_ixy*left_sign}" ixz="${foot_motor_ixz}" iyy="${foot_motor_iyy}" iyz="${foot_motor_iyz*left_sign}" izz="${foot_motor_izz}" />
      </inertial>
      <collision>
        <origin rpy="${PI/2.0} 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${foot_motor_length}" radius="${foot_motor_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_foot_motor_joint" type="fixed">
      <origin xyz="${foot_motor_offset_x} ${foot_motor_offset_y*left_sign} ${foot_motor_offset_z}" rpy="0 0.0 0" />
      <parent link="${prefix}_calf" />
      <child link="${prefix}_foot_motor" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- Foot -->
    <link name="${prefix}_foot">
      <inertial>
        <origin xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}" rpy="0 0 0" />
        <mass value="${foot_mass}" />
        <inertia ixx="${foot_ixx}" ixy="${foot_ixy}" ixz="${foot_ixz}" iyy="${foot_iyy}" iyz="${foot_iyz}" izz="${foot_izz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <xacro:if value="${left == True}">
            <mesh filename="${mesh_prefix}/left_wheel.dae" />
            </xacro:if>
            <xacro:if value="${left == False}">
            <mesh filename="${mesh_prefix}/right_wheel.dae" />
            </xacro:if>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="${PI/2.0} 0 0" xyz="0 ${foot_offset_col_y*left_sign} 0" />
        <geometry>
          <cylinder length="${foot_length}" radius="${foot_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_foot_joint" type="continuous">
      <origin xyz="${foot_offset_x} ${foot_offset_y*left_sign} ${foot_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}_calf" />
      <child link="${prefix}_foot" />
      <axis xyz="0 1 0" />
      <limit effort="${foot_torque_max}" velocity="${foot_velocity_max}" />
    </joint>
    <gazebo reference="${prefix}_foot">
        <mu1>3</mu1>
        <mu2>3</mu2>
    </gazebo>

  </xacro:macro>


  <!-- Base-->
  <link name="base_link"/>

  <!-- Body -->
  <link name="body">
    <inertial>
      <origin xyz="${body_com_x} ${body_com_y} ${body_com_z}" rpy="0 0 0" />
      <mass value="${body_mass}" />
      <inertia ixx="${body_ixx}" ixy="${body_ixy}" ixz="${body_ixz}" iyy="${body_iyy}" iyz="${body_iyz}" izz="${body_izz}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="${mesh_prefix}/base.dae" />
      </geometry>
      <material name="深色橡胶_001-effect"><color rgba="0.6717055 0.6924257 0.7742702 1" /></material><material name="白色logo_001-effect"><color rgba="1 1 1 1" /></material><material name="黑色贴纸_007-effect"><color rgba="0.009018 0.009018 0.009018 1" /></material><material name="黑色金属_007-effect"><color rgba="0.01341 0.01341 0.01341 1" /></material><material name="黑色塑料_003-effect"><color rgba="0.023455 0.023455 0.023455 1" /></material></visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_width}" />
      </geometry>
    </collision>
  </link>
  <joint name="body_joint" type="fixed">
    <parent link="base_link" />
    <child link="body" />
  </joint>

  <!-- Head Upper-->
  <link name="Head_upper">
    <inertial>
      <origin xyz="${head_upper_com_x} ${head_upper_com_y} ${head_upper_com_z}" rpy="0 0 0" />
      <mass value="${head_upper_mass}" />
      <inertia ixx="${head_upper_ixx}" ixy="${head_upper_ixy}" ixz="${head_upper_ixz}" iyy="${head_upper_iyy}" iyz="${head_upper_iyz}" izz="${head_upper_izz}" />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${head_upper_radius}" length="${head_upper_length}" />
      </geometry>
    </collision>
  </link>
  <joint name="Head_upper_joint" type="fixed" dont_collapse="true">
    <origin xyz="0.285 0 0.01" rpy="0 0 0" />
    <parent link="body" />
    <child link="Head_upper" />
    <axis xyz="0 0 0" />
  </joint>

  <!-- Head Lower -->
  <link name="Head_lower">
    <inertial>
      <origin xyz="${head_lower_com_x} ${head_lower_com_y} ${head_lower_com_z}" rpy="0 0 0" />
      <mass value="${head_lower_mass}" />
      <inertia ixx="${head_lower_ixx}" ixy="${head_lower_ixy}" ixz="${head_lower_ixz}" iyy="${head_lower_iyy}" iyz="${head_lower_iyz}" izz="${head_lower_izz}" />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${head_lower_radius}" />
      </geometry>
    </collision>
  </link>
  <joint name="Head_lower_joint" type="fixed" dont_collapse="true">
    <origin xyz="0.008 0 -0.07" rpy="0 0 0" />
    <parent link="Head_upper" />
    <child link="Head_lower" />
    <axis xyz="0 0 0" />
  </joint>
  
  <xacro:leg prefix="FL" front="True" left="True"/>
  <xacro:leg prefix="FR" front="True" left="False"/>
  <xacro:leg prefix="RL" front="False" left="True"/>
  <xacro:leg prefix="RR" front="False" left="False"/>

  <!-- IMU -->
  <!-- <link name="imu">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="-0.02557 0 0.04232" rpy="0 0 0" />
    <parent link="body" />
    <child link="imu" />
    <axis xyz="0 0 0" />
  </joint>
  <gazebo reference="imu">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <imu>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </z>
        </linear_acceleration>
      </imu>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <namespace>imu</namespace>
          <remapping>~/out:=data</remapping>
        </ros>
        <frameName>imu</frameName>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
    </sensor>
  </gazebo> -->

  <!-- Lidar -->
  <!-- <link name="lidar">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <origin xyz="0.28945 0 -0.046825" rpy="${PI} 2.8782 0" />
    <parent link="body" />
    <child link="lidar" />
    <axis xyz="0 0 0" />
  </joint>
  <gazebo reference="lidar">
    <sensor name="unitree_lidar_l1" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>18</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>${-PI/2.0 + 1.0}</min_angle>
            <max_angle>${-PI/2.0 + 1.7}</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>40.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_ray_sensor" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>lidar</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <frame_name>lidar</frame_name>
      </plugin>
    </sensor>
  </gazebo> -->




  <!-- =============== mid360 ============ -->
  <!-- <origin xyz="0.3 0.0 0.10" rpy="0 0.5235987756 0"/> -->
  <!-- <xacro:include filename="$(find go2w_description)/urdf/sensor/mid360_gpu.xacro"/> 
  <xacro:mid360  name="livox_frame" parent="body" topic="/livox/lidar" imu_topic="/livox/imu" >
    <origin xyz="0.3 0.0 0.10" rpy="0 0.0 0"/>
  </xacro:mid360>  -->





  <!-- Camera -->
  <link name="camera">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link> -->
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.325 0 0.043" rpy="0 0 0" />
    <parent link="body" />
    <child link="camera" />
    <axis xyz="0 0 0" />
  </joint>
  <gazebo reference="camera">
    <sensor name="camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>2.0944</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100.0</far>
        </clip>
      </camera>
      <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
        <frame_name>camera</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Gazebo ros2_control -->
  <ros2_control name="gazebo_ros2_control" type="system">
    <hardware>
    <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <xacro:macro name="joint_ros2_control" params="prefix">
      <joint name="${prefix}_hip_joint">
        <command_interface name="effort">
          <param name="min">${-hip_torque_max}</param>
          <param name="max">${hip_torque_max}</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">${hip_init_position}</param>
        </state_interface>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
        
      <joint name="${prefix}_thigh_joint">
        <command_interface name="effort">
          <param name="min">${-thigh_torque_max}</param>
          <param name="max">${thigh_torque_max}</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">${thigh_init_position}</param>
        </state_interface>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
        
      <joint name="${prefix}_calf_joint">
        <command_interface name="effort">
          <param name="min">${-calf_torque_max}</param>
          <param name="max">${calf_torque_max}</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">${calf_init_position}</param>
        </state_interface>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>

      <joint name="${prefix}_foot_joint">
        <command_interface name="velocity">
          <param name="min">${-foot_velocity_max}</param>
          <param name="max">${foot_velocity_max}</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="effort"/>
      </joint>
    </xacro:macro>

    <xacro:joint_ros2_control prefix="FL"/>
    <xacro:joint_ros2_control prefix="FR"/>
    <xacro:joint_ros2_control prefix="RL"/>
    <xacro:joint_ros2_control prefix="RR"/>

  </ros2_control>

  <!-- Gazebo plugin for ros2_control -->
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find go2w_description)/config/joint_controller.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Gazebo Odometry Publisher Plugin - 发布机器狗真实位姿 -->
  <gazebo>
    <plugin filename="libgazebo_odometry_publisher.so" name="odometry_publisher">
      <!-- 发布频率 (Hz) -->
      <update_rate>30</update_rate>
      
      <!-- 参考坐标系 -->
      <frame_name>odom</frame_name>
      
      <!-- 机器狗本体坐标系 -->
      <body_name>base_footprint</body_name>
      
      <!-- 发布的话题名称 -->
      <topic_name>/gazebo/tower/go2w/odometry</topic_name>
      
      <!-- 坐标系设置 -->
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
      
      <!-- 高斯噪声设置 (可选) -->
      <gaussian_noise>0.001</gaussian_noise>
      
      <!-- 是否发布tf变换 -->
      <publish_tf>true</publish_tf>
      
      <!-- 坐标系前缀 -->
      <frame_prefix></frame_prefix>
    </plugin>
  </gazebo>

  <!-- Sensors -->
  <!-- <xacro:include filename="$(find go2_description)/xacro/velodyne.xacro"/> -->
  <xacro:include filename="$(find go2_description)/xacro/gps.xacro"/>
  <!-- <xacro:include filename="$(find ros2_livox_simulation)/urdf/mid360.xacro"/> -->
  <xacro:include filename="$(find mid360_simulation)/urdf/mid360.xacro"/> 
  <!-- <xacro:include filename="$(find go2_description)/xacro/laser.xacro"/> -->

  <!-- GPS Sensor -->
  <xacro:gps_sensor name="gps" parent_link="body">
      <origin xyz="-0.1 0 0.06" rpy="0 0 0"/>
  </xacro:gps_sensor>

  <xacro:mid360 name="livox_frame" parent="body">
      <origin xyz="0.25 0 0.13" rpy="0 0.4 0"/>
  </xacro:mid360>

</robot>